# devH2 -- H2 development profile
management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
    beans:
      enabled: true

spring:
  include:
    - default

  datasource:
    #    driver-class-name: org.h2database.jdbcDriver
    url: jdbc:h2:mem:dmc
    #    url: jdbc:h2:file:./h2-db/app_db;AUTO_SERVER=TRUE
    username: sa

# for H2 console frame
security:
  headers:
    frame: false

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: WARN
    org.springframework.data: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.webflow: TRACE
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    evm.dmc.web: TRACE
    evm.dmc.api: DEBUG

