spring:
  include:
    - default

  datasource:
    #    driver-class-name: org.h2database.jdbcDriver
    url: jdbc:h2:file:./h2-db/app_db;AUTO_SERVER=TRUE
  #    url: jdbc:h2:mem:dmc
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  allowed:
    resources: /h2-console/**

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: DEBUG
    #    org.springframework.security: WARN
    org.springframework.data: TRACE
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    evm.dmc.rest: TRACE
    evm.dmc.api: DEBUG

# for H2 console frame
security:
  basic:
    enabled: true
    authorize-mode: NONE
  headers:
    frame: false